### ISSUE TITLE
关于布局比例、纪元、事件条的建议

### ISSUE THREAD

**Issue by Hyd19** [choyy/Timeline-SY#10]
1. 时间轴上下空间的分配比例能不能自由调整？事件多了之后会很密集地重叠。将界面放大后，比例会失调，时间轴下方空间比上方增加更大。
2. 时间轴和纪元能否添加多条，对比不同地区的发展时期？
3. 鼠标在事件块上悬停时，显示具体时间？这样可以不用频繁点击、上下切换视线来查询具体时间。

**Comment by choyy** [comment]
1. 这个我有空加个设置
2. 这个不能
3. 时间轴上就能看到时间啊，如果要看到具体时间就只能放大或者切换了

**Comment by Hyd19** [comment]
> 1. 这个我有空加个设置
> 2. 这个不能
> 3. 时间轴上就能看到时间啊，如果要看到具体时间就只能放大或者切换了

那事件条可以同纪元一样添加颜色吗？这样就可以把不同时期以染色的事件条展示，在大量事件中快速定位。

**Comment by choyy** [comment]
![图片](https://user-images.githubusercontent.com/68107073/181519654-5e5ab631-9ea1-4aa1-a7eb-306f44dc5d2e.png)
倒是有个相似的功能：分组
可以给事件添加一个分组，同一分组的事件会显示在同一行（如上图中的分组1、分组2），没有分组的会显示在最下面。这个东西的缺点是某一分组的事件很少它也会占一行的空间，比较浪费空间

**Comment by choyy** [comment]
添加颜色的话，似乎好像也可以实现🤔

**Comment by Hyd19** [comment]
> ![图片](https://user-images.githubusercontent.com/68107073/181519654-5e5ab631-9ea1-4aa1-a7eb-306f44dc5d2e.png) 倒是有个相似的功能：分组 可以给事件添加一个分组，同一分组的事件会显示在同一行（如上图中的分组1、分组2），没有分组的会显示在最下面。这个东西的缺点是某一分组的事件很少它也会占一行的空间，比较浪费空间

- 这个分组功能挺好的，事件可以集中，连贯性强，期待能够加入😮
- 我之前建议的鼠标悬停显示时间也是考虑到空间的问题。如果事件多了，可能和时间轴相距很远，甚至时间轴会超过屏幕显示范围，就不方便观察了。如果能悬停显示（或者配合按键触发，像鼠标取词那种），对时间轴的依赖性就小了，空间安排更自由。当然这是设想，不知道有没有可行性😂
