### ISSUE TITLE
可以支持只输入年份以及只有年份和月份吗？

### ISSUE THREAD

**Issue by tcmtom** [choyy/Timeline-SY#16]
![image](https://user-images.githubusercontent.com/94541098/212465586-82c033b0-3221-42ea-a8a7-e345986d6516.png)
如图，月份和日子都输入了0
![image](https://user-images.githubusercontent.com/94541098/212465677-86b84d1f-690c-41fe-8dc4-bb8ba466d628.png)
实际显示

**Comment by choyy** [comment]
别输0，啥都别输
