### ISSUE TITLE
集市打包报错

### ISSUE THREAD

**Issue by 88250** [choyy/Timeline-SY#18]
你好，现在的版本集市打包一直报错，麻烦处理一下：

![image](https://github.com/choyy/Timeline-SY/assets/873584/6a539764-046d-4176-b389-a6c177adbed4)

![image](https://github.com/choyy/Timeline-SY/assets/873584/aca0afed-fee6-49d9-8897-d19e9d5b73d7)

**Comment by choyy** [comment]
现在好了吧

**Comment by 88250** [comment]
好了，后面建议升级到新的集市打包，即上传 package.zip 的方式，因为后续我们会逐步移除旧的打包上架方式，谢谢。

**Comment by choyy** [comment]
Source code (zip) 不行吗，还是必须得上传一个 package.zip

**Comment by 88250** [comment]
源码包不行，必须上传打包好的 package.zip

**Comment by choyy** [comment]
源码包就是 package.zip只不过多了widget.json readme这些东西ヽ(ー_ー)ノ

**Comment by 88250** [comment]
请看 https://github.com/siyuan-note/widget-sample 以了解打包结构

**Comment by choyy** [comment]
那源码包就完完全全是package.zip了ヽ(ー_ー)ノ

**Comment by choyy** [comment]
等加个icon.png
