### ISSUE TITLE
关联思源笔记内容

### ISSUE THREAD

**Issue by AdachiQ** [choyy/Timeline-SY#2]
能否关联到思源笔记的文档或块呢？点击标题跳转到文档和块，以便查看详细内容。

**Comment by choyy** [comment]
我也非常想这样，但我不知道怎么实现

**Comment by choyy** [comment]
v0.0.3 勉强支持通过超链接跳转到思源内容块

**Comment by leolee9086** [comment]
https://github.com/choyy/Timeline-SY/pull/7  我试着实现了一下,你看一下行不行哒

**Comment by choyy** [comment]
> #7 我试着实现了一下,你看一下行不行哒

这个功能顶！在v0.0.5更新了

**Comment by choyy** [comment]
v0.0.7 完全支持直接插入以及markdown语法插入思源块超链接
