### ISSUE TITLE
widget.json name字段好像有点问题

### ISSUE THREAD

**Issue by leolee9086** [choyy/Timeline-SY#3]

**Comment by leolee9086** [comment]
timeline-beta 是不是应该是 timeline-sy

**Comment by leolee9086** [comment]
![image](https://user-images.githubusercontent.com/19915077/169802835-d84a9016-17ce-453a-ba01-e6dd2c734e84.png)

**Comment by choyy** [comment]
哦哦，我以为那只是在集市展示的名字
