### ISSUE TITLE
可以通过解析url参数达成在浏览器打开窗口

### ISSUE THREAD

**Issue by leolee9086** [choyy/Timeline-SY#4]
var id = ''
if(window.frameElement){
var id = window.frameElement.parentElement.parentElement.dataset.nodeId;
}
else{
    const search = location.search
    const obj = new URLSearchParams(search);
    id =  obj.get('blockid')
}

**Comment by leolee9086** [comment]
![image](https://user-images.githubusercontent.com/19915077/169803800-a5d79edb-abdb-4f86-b53c-8181fed9bf66.png)

**Comment by leolee9086** [comment]
这样在浏览器打开可能空间更大一点

**Comment by choyy** [comment]
为什么我加不加那段代码在浏览器打开都是一样的

**Comment by leolee9086** [comment]
加了之后可以通过http://192.168.0.9:6806/widgets/Timelline-SY?blockid=<挂件id>访问某个挂件的数据

**Comment by leolee9086** [comment]
![image](https://user-images.githubusercontent.com/19915077/169810906-d80afb33-3ac0-4ca3-8329-645f66bef613.png)

**Comment by choyy** [comment]
我是127.0.0.1本地访问是一样的，你那个不一样吗

**Comment by leolee9086** [comment]
https://github.com/choyy/Timelline-SY/pull/5
详细的可以参考我发起的这个pr
